export * from './contacto.vo';
export * from './direccion.vo';
export * from './embalaje.vo';
export * from './id.vo';
export * from './numeroRastreo.vo';
export * from './situacion.vo';
export * from './telefono.vo';
export * from './tipoIncidencia.vo';
export * from './valorDeclarado.vo';
